---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: "RABBITMQ_ERLANG_COOKIE"
              value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          ports:
            - containerPort: 15672
              name: main
              protocol: TCP
            - containerPort: 5672
              name: messages
              protocol: TCP
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: earth-queue-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30008
    - name: messages
      protocol: TCP
      port: 5672
      targetPort: 5672

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: earth-bridge-deployment
spec:
  selector:
    matchLabels:
      app: earth-bridge
  template:
    metadata:
      labels:
        app: earth-bridge
    spec:
      initContainers:
        - name: wait-for-other-pod
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://rabbitmq:5672" -o /dev/null) -ne 200 ]; do
                sleep 15;
              done
      containers:
        - name: earth-deployment
          image: endienasg/earthbridge:master
          imagePullPolicy: Always
          ports:
            - containerPort: 25575

---
apiVersion: v1
kind: Service
metadata:
  name: earth-bridge-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: ClusterIP
  selector:
    app: earth-bridge
  ports:
    - name: udp
      protocol: UDP
      port: 25575
      targetPort: 25575
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: space
            - name: POSTGRES_USER
              value: foxstudios
            - name: POSTGRES_PASSWORD
              value: root
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "mendix-pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: mendix-pgdata
  selector:
    matchLabels:
      app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: earth-db-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30012

---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: earth-rest-deployment
spec:
  selector:
    matchLabels:
      app: earth-rest
  template:
    metadata:
      labels:
        app: earth-rest
    spec:
      initContainers:
        - name: wait-for-other-pod
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://earth-db-service:5432" -o /dev/null) -ne 200 ]; do
                sleep 15;
              done
      containers:
        - name: earth-rest-deployment
          image: endienasg/earthrestproject:master
          imagePullPolicy: Always
          ports:
            - containerPort: 25576

---
apiVersion: v1
kind: Service
metadata:
  name: earth-rest-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: ClusterIP
  selector:
    app: earth-rest
  ports:
    - name: http
      protocol: TCP
      port: 25576
      targetPort: 25576
