apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-pusher-deployment
spec:
  selector:
    matchLabels:
      app: mars-pusher
  template:
    metadata:
      labels:
        app: mars-pusher
    spec:
      initContainers:
        - name: wait-for-other-pod
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://rabbitmq:5672" -o /dev/null) -ne 200 ]; do
                sleep 15;
              done
      containers:
        - name: marspusherpod-failed
          image: endienasg/marspusher:master
          imagePullPolicy: Always
          env:
            - name: "RABBIT_MQ_PASSWORD"
              value: "guest"
            - name: "RABBIT_MQ_LOGIN"
              value: "guest"
          ports:
            - containerPort: 25565

---
apiVersion: v1
kind: Service
metadata:
  name: mars-listener-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: ClusterIP
  selector:
    app: mars-pusher
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 25565
  clusterIP: 10.96.0.12
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          env:
            - name: "RABBITMQ_ERLANG_COOKIE"
              value: "1WqgH8N2v1qDBDZDbNy8Bg9IkPWLEpu79m6q+0t36lQ="
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data
          ports:
            - containerPort: 15672
              name: main
              protocol: TCP
            - containerPort: 5672
              name: messages
              protocol: TCP
      volumes:
        - name: rabbitmq-data
          hostPath:
            path: /data/rabbitmq
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: mars-queue-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: messages
      protocol: TCP
      port: 5672
      targetPort: 5672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mars-bridge-deployment
spec:
  selector:
    matchLabels:
      app: mars-bridge
  template:
    metadata:
      labels:
        app: mars-bridge
    spec:
      initContainers:
        - name: wait-for-other-pod
          image: busybox
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ $(curl -sw '%{http_code}' "http://rabbitmq:5672" -o /dev/null) -ne 200 ]; do
                sleep 15;
              done
      containers:
        - name: marsbridge-deployment
          image: endienasg/marsbridge:master
          imagePullPolicy: Always
          ports:
            - containerPort: 25575

---
apiVersion: v1
kind: Service
metadata:
  name: mars-bridge-service
  labels:
    env: prod
    owner: endienasg
spec:
  type: ClusterIP
  selector:
    app: mars-bridge
  ports:
    - name: udp
      protocol: UDP
      port: 25575
      targetPort: 25575
---
#test
